import { WAVE_CURVES } from '../../balance/waves';
import type { MapDef } from '../../balance/types';

// Grid is 30 x 14 tiles. Waypoints are tile coordinates; the first may sit just off-grid so enemies walk in.
export const SPACE_MAPS: MapDef[] = [
  {
    id: 'station',
    name: 'Station Corridor',
    subtitle: 'Sector 7 maintenance ring',
    theme: 'station',
    waypoints: [[-1, 2], [6, 2], [6, 10], [14, 10], [14, 3], [22, 3], [22, 11], [27, 11]],
    startingCash: 150,
    music: 'station',
    waves: WAVE_CURVES[0],
    metaPerWave: 2,
    firstClearBonus: 20,
    seed: 101,
    introduces: ['scout', 'armored', 'grunt'],
  },
  {
    id: 'asteroid',
    name: 'Asteroid Mine',
    subtitle: 'Kessler belt dig site',
    theme: 'asteroid',
    waypoints: [[30, 1], [23, 1], [23, 6], [16, 6], [16, 12], [8, 12], [8, 3], [3, 3], [3, 10]],
    startingCash: 200,
    music: 'asteroid',
    waves: WAVE_CURVES[1],
    metaPerWave: 3,
    firstClearBonus: 30,
    seed: 202,
    introduces: ['shielded'],
  },
  {
    id: 'derelict',
    name: 'Derelict Ship',
    subtitle: 'Hull of the ISV Meridian',
    theme: 'derelict',
    waypoints: [[-1, 7], [4, 7], [4, 1], [11, 1], [11, 12], [18, 12], [18, 1], [25, 1], [25, 7], [28, 7]],
    startingCash: 260,
    music: 'derelict',
    waves: WAVE_CURVES[2],
    metaPerWave: 3,
    firstClearBonus: 40,
    seed: 303,
    introduces: ['splitter', 'stealth'],
  },
  {
    id: 'planet',
    name: 'Planetary Outpost',
    subtitle: 'Red dunes of Tessaly IV',
    theme: 'planet',
    waypoints: [[3, -1], [3, 5], [10, 5], [10, 1], [17, 1], [17, 9], [7, 9], [7, 12], [24, 12], [24, 4], [27, 4]],
    startingCash: 320,
    music: 'planet',
    waves: WAVE_CURVES[3],
    metaPerWave: 4,
    firstClearBonus: 50,
    seed: 404,
    introduces: ['healer'],
  },
  {
    id: 'orbital',
    name: 'Orbital Platform',
    subtitle: 'Last line above Earth',
    theme: 'orbital',
    waypoints: [[-1, 11], [5, 11], [5, 2], [12, 2], [12, 8], [20, 8], [20, 2], [26, 2], [26, 11], [28, 11]],
    startingCash: 500,
    music: 'orbital',
    waves: WAVE_CURVES[4],
    metaPerWave: 4,
    firstClearBonus: 60,
    seed: 505,
    introduces: [],
  },
];
