import { SCALES, type TrackDef } from '../../../assets/audio/tracks';

/** Keys are `menu` plus one per map id. */
export const SPACE_TRACKS: Record<string, TrackDef> = {
  menu: {
    bpm: 96,
    root: 69,
    scale: SCALES.minor,
    progression: [0, 5, 3, 4],
    drums: 'k.......s.......',
    bass: 'x.......x...o...',
    lead: 'triangle',
    arp: true,
    density: 0.35,
    seed: 11,
  },
  station: {
    bpm: 120,
    root: 62,
    scale: SCALES.minor,
    progression: [0, 0, 5, 6],
    drums: 'k.h.s.h.k.h.s.hh',
    bass: 'x.x.o.x.x.x.o.x.',
    lead: 'square',
    arp: false,
    density: 0.5,
    seed: 21,
  },
  asteroid: {
    bpm: 112,
    root: 64,
    scale: SCALES.dorian,
    progression: [0, 3, 0, 4],
    drums: 'k..hs..hk.k.s..h',
    bass: 'x..x..o.x..x..o.',
    lead: 'square',
    arp: true,
    density: 0.45,
    seed: 32,
  },
  derelict: {
    bpm: 92,
    root: 60,
    scale: SCALES.phrygian,
    progression: [0, 1, 0, 6],
    drums: 'k.......s..h....',
    bass: 'x...x...x...o...',
    lead: 'triangle',
    arp: true,
    density: 0.3,
    seed: 43,
  },
  planet: {
    bpm: 128,
    root: 65,
    scale: SCALES.mixolydian,
    progression: [0, 6, 5, 4],
    drums: 'k.hhs.hhk.hhs.hk',
    bass: 'x.xox.xox.xox.xo',
    lead: 'square',
    arp: false,
    density: 0.55,
    seed: 54,
  },
  orbital: {
    bpm: 140,
    root: 67,
    scale: SCALES.harmonicMinor,
    progression: [0, 5, 3, 4],
    drums: 'k.hks.h.k.hks.hs',
    bass: 'xxo.xxo.xxo.xxox',
    lead: 'sawtooth',
    arp: true,
    density: 0.6,
    seed: 65,
  },
};
