import type { MapDef } from '../../balance/types';
import { WAVE_CURVES } from '../../balance/waves';

// Grid is 30 x 14 tiles. Layouts are this world's own — only the wave curves are shared.
export const WEST_MAPS: MapDef[] = [
  {
    id: 'mainstreet',
    name: 'Perdition Flats',
    subtitle: 'One street, two saloons',
    theme: 'mainstreet',
    waypoints: [[-1, 3], [8, 3], [8, 10], [16, 10], [16, 2], [24, 2], [24, 11], [27, 11]],
    startingCash: 150,
    music: 'mainstreet',
    waves: WAVE_CURVES[0],
    metaPerWave: 2,
    firstClearBonus: 20,
    seed: 121,
    introduces: ['scout', 'armored', 'grunt'],
  },
  {
    id: 'canyon',
    name: 'Dead Man Canyon',
    subtitle: 'The only way through the rocks',
    theme: 'canyon',
    waypoints: [[30, 2], [23, 2], [23, 9], [15, 9], [15, 3], [7, 3], [7, 11], [2, 11]],
    startingCash: 200,
    music: 'canyon',
    waves: WAVE_CURVES[1],
    metaPerWave: 3,
    firstClearBonus: 30,
    seed: 232,
    introduces: ['shielded'],
  },
  {
    id: 'goldmine',
    name: 'The Widowmaker',
    subtitle: 'Deepest shaft in the territory',
    theme: 'goldmine',
    waypoints: [[-1, 6], [5, 6], [5, 1], [12, 1], [12, 12], [19, 12], [19, 1], [25, 1], [25, 8], [28, 8]],
    startingCash: 260,
    music: 'goldmine',
    waves: WAVE_CURVES[2],
    metaPerWave: 3,
    firstClearBonus: 40,
    seed: 343,
    introduces: ['splitter', 'stealth'],
  },
  {
    id: 'prairie',
    name: 'Open Prairie',
    subtitle: 'Nothing between you and them',
    theme: 'prairie',
    waypoints: [[-1, 2], [23, 2], [23, 5], [5, 5], [5, 8], [25, 8], [25, 11], [3, 11], [3, 13], [28, 13]],
    startingCash: 320,
    music: 'prairie',
    waves: WAVE_CURVES[3],
    metaPerWave: 4,
    firstClearBonus: 50,
    seed: 454,
    introduces: ['healer'],
  },
  {
    id: 'railjunction',
    name: 'Rail Junction',
    subtitle: 'Where every line meets',
    theme: 'railjunction',
    waypoints: [[-1, 7], [5, 7], [5, 1], [12, 1], [12, 12], [19, 12], [19, 2], [26, 2], [26, 10], [29, 10]],
    startingCash: 500,
    music: 'railjunction',
    waves: WAVE_CURVES[4],
    metaPerWave: 4,
    firstClearBonus: 60,
    seed: 565,
    introduces: [],
  },
];
