import type { PixelArt } from '../../../assets/pixel';
import { C, SPACE_ART_PALETTE as P } from './palette';

export const SPACE_DECOR: Record<string, PixelArt> = {
  decor_crate: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, R: '#8a5a3a', y: '#c28a4a' },
    frames: [['........', '........', '..oooooo', '..oRRRRR', '..oRyRRR', '..oRRyRR', '..oRRRyR', '..oRRRRy']],
  },
  decor_console: {
    mirrorX: true,
    palette: P,
    frames: [
      [
        '........',
        '........',
        '........',
        '..oooooo',
        '.odddddd',
        '.odbBbBb',
        '.odbbbbb',
        '.odGdrdy',
        '.odddddd',
        '.odddddd',
        '..oooooo',
        '...o....',
        '...o....',
        '........',
        '........',
        '........',
      ],
    ],
  },
  decor_rock: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, m: '#6b4f4f', l: '#8a6f5a', d: '#3b2e2e' },
    frames: [['........', '........', '........', '.....ooo', '...oommm', '..ommlll', '..omlllm', '.omllmmm']],
  },
  decor_rock_red: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, m: '#6e2f2a', l: '#9c4a3a', d: '#3e1d1b' },
    frames: [['........', '........', '........', '.....ooo', '...oommm', '..ommlll', '..omlllm', '.omllmmm']],
  },
  decor_crystal: {
    mirrorX: true,
    palette: P,
    frames: [
      [
        '........',
        '.......o',
        '......oc',
        '......oc',
        '.....ocB',
        '..o..ocB',
        '.oco.ocB',
        '.ocBooBB',
        '.oBBoBBb',
        '..oBBBbb',
        '..oBBbbb',
        '...obbbb',
        '...ooooo',
        '........',
        '........',
        '........',
      ],
    ],
  },
  decor_debris: {
    palette: { ...P, d: '#2b3b3a', m: '#3a4f4c', r: '#7a4a2a' },
    frames: [
      [
        '................',
        '................',
        '....oo..........',
        '...omdo.....o...',
        '...oddo....omo..',
        '....oo.....oddo.',
        '...........oo...',
        '......ooo.......',
        '.....ommmoo.....',
        '....omdddmmo....',
        '....odddrddo....',
        '.....oodddo.....',
        '.......ooo......',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_pipe: {
    palette: { ...P, m: '#3a4f4c', l: '#5b7a74', d: '#1f2a2a' },
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        'oooooooooooooooo',
        'lllllllooollllll',
        'mmmmmmmoRommmmmm',
        'mmmmmmmoRommmmmm',
        'dddddddooodddddd',
        'oooooooooooooooo',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_antenna: {
    mirrorX: true,
    palette: { ...P, w: C.red },
    frames: [
      [
        '........',
        '.......w',
        '.......o',
        '.......o',
        '....oooo',
        '...ollll',
        '..olmmmm',
        '...ooooo',
        '.......o',
        '.......o',
        '......oo',
        '.....omm',
        '....ommm',
        '...ommmm',
        '...ooooo',
        '........',
      ],
    ],
  },
};
