import { SCALES, type TrackDef } from '../../../assets/audio/tracks';

/** Minor-key marches on a military kit: heavy kick, rolling snare, low sawtooth bass. */
export const WW2_TRACKS: Record<string, TrackDef> = {
  menu: {
    bpm: 88,
    root: 64,
    scale: SCALES.minor,
    progression: [0, 0, 5, 4],
    drums: 'k...s...k...s...',
    bass: 'x.......x.......',
    lead: 'triangle',
    arp: false,
    density: 0.3,
    seed: 12,
    kit: 'military',
    bassWave: 'sawtooth',
  },
  hedgerow: {
    bpm: 108,
    root: 62,
    scale: SCALES.minor,
    progression: [0, 3, 0, 4],
    drums: 'k.s.k.s.k.s.k.ss',
    bass: 'x.x.x.x.o.o.x.x.',
    lead: 'triangle',
    arp: false,
    density: 0.45,
    seed: 22,
    kit: 'military',
    bassWave: 'sawtooth',
  },
  stalingrad: {
    bpm: 96,
    root: 59,
    scale: SCALES.phrygian,
    progression: [0, 1, 0, 6],
    drums: 'k.......s.h.s...',
    bass: 'x...x...x...o...',
    lead: 'sawtooth',
    arp: false,
    density: 0.35,
    seed: 33,
    kit: 'military',
    bassWave: 'sawtooth',
  },
  ardennes: {
    bpm: 84,
    root: 57,
    scale: SCALES.harmonicMinor,
    progression: [0, 5, 3, 0],
    drums: 'k.......s.......',
    bass: 'x.......o.......',
    lead: 'triangle',
    arp: true,
    density: 0.28,
    seed: 44,
    kit: 'military',
    arpWave: 'triangle',
  },
  desert: {
    bpm: 124,
    root: 65,
    scale: SCALES.dorian,
    progression: [0, 6, 5, 4],
    drums: 'k.hks.hkk.hks.hs',
    bass: 'x.xox.xox.xox.xo',
    lead: 'square',
    arp: false,
    density: 0.55,
    seed: 55,
    kit: 'military',
    bassWave: 'sawtooth',
  },
  rhine: {
    bpm: 132,
    root: 62,
    scale: SCALES.harmonicMinor,
    progression: [0, 5, 6, 4],
    drums: 'k.sks.shk.sks.ss',
    bass: 'xxo.xxo.xxo.xxox',
    lead: 'sawtooth',
    arp: true,
    density: 0.6,
    seed: 66,
    kit: 'military',
    bassWave: 'sawtooth',
  },
};
