import { SCALES, type TrackDef } from '../../../assets/audio/tracks';

/** Pentatonic and mixolydian twang over a stomp-and-woodblock kit. */
export const WEST_TRACKS: Record<string, TrackDef> = {
  menu: {
    bpm: 92,
    root: 67,
    scale: SCALES.majorPentatonic,
    progression: [0, 4, 3, 0],
    drums: 'k.......h.......',
    bass: 'x.......o.......',
    lead: 'triangle',
    arp: false,
    density: 0.3,
    seed: 13,
    kit: 'western',
  },
  mainstreet: {
    bpm: 116,
    root: 65,
    scale: SCALES.mixolydian,
    progression: [0, 0, 4, 3],
    drums: 'k.h.s.h.k.h.s.h.',
    bass: 'x.o.x.o.x.o.x.o.',
    lead: 'square',
    arp: false,
    density: 0.5,
    seed: 23,
    kit: 'western',
  },
  canyon: {
    bpm: 84,
    root: 62,
    scale: SCALES.minor,
    progression: [0, 5, 0, 4],
    drums: 'k.....h.s.....h.',
    bass: 'x.......x...o...',
    lead: 'triangle',
    arp: true,
    density: 0.28,
    seed: 34,
    kit: 'western',
    arpWave: 'triangle',
  },
  goldmine: {
    bpm: 100,
    root: 60,
    scale: SCALES.dorian,
    progression: [0, 3, 6, 4],
    drums: 'k..hs..hk..hs.hh',
    bass: 'x..x..o.x..x..o.',
    lead: 'square',
    arp: true,
    density: 0.42,
    seed: 45,
    kit: 'western',
  },
  prairie: {
    bpm: 128,
    root: 69,
    scale: SCALES.majorPentatonic,
    progression: [0, 4, 3, 4],
    drums: 'k.hhs.hhk.hhs.hk',
    bass: 'x.xox.xox.xox.xo',
    lead: 'square',
    arp: false,
    density: 0.55,
    seed: 56,
    kit: 'western',
  },
  railjunction: {
    bpm: 144,
    root: 64,
    scale: SCALES.harmonicMinor,
    progression: [0, 5, 3, 4],
    drums: 'k.hks.hkk.hks.hs',
    bass: 'xxo.xxo.xxo.xxox',
    lead: 'sawtooth',
    arp: true,
    density: 0.6,
    seed: 67,
    kit: 'western',
  },
};
