import type { MapDef } from '../../balance/types';
import { WAVE_CURVES } from '../../balance/waves';

// Grid is 30 x 14 tiles. Layouts are this world's own — only the wave curves are shared.
export const WW2_MAPS: MapDef[] = [
  {
    id: 'hedgerow',
    name: 'Hedgerow Country',
    subtitle: 'Bocage south of the beachhead',
    theme: 'hedgerow',
    waypoints: [[-1, 11], [7, 11], [7, 4], [15, 4], [15, 11], [23, 11], [23, 5], [27, 5]],
    startingCash: 150,
    music: 'hedgerow',
    waves: WAVE_CURVES[0],
    metaPerWave: 2,
    firstClearBonus: 20,
    seed: 111,
    introduces: ['scout', 'armored', 'grunt'],
  },
  {
    id: 'stalingrad',
    name: 'Factory District',
    subtitle: 'Rubble on the east bank',
    theme: 'stalingrad',
    waypoints: [[30, 12], [24, 12], [24, 2], [17, 2], [17, 9], [10, 9], [10, 2], [4, 2], [4, 8], [2, 8]],
    startingCash: 200,
    music: 'stalingrad',
    waves: WAVE_CURVES[1],
    metaPerWave: 3,
    firstClearBonus: 30,
    seed: 222,
    introduces: ['shielded'],
  },
  {
    id: 'ardennes',
    name: 'Ardennes Forest',
    subtitle: 'Fog, snow and no air cover',
    theme: 'ardennes',
    waypoints: [[-1, 1], [5, 1], [5, 8], [12, 8], [12, 1], [19, 1], [19, 11], [26, 11], [26, 5], [28, 5]],
    startingCash: 260,
    music: 'ardennes',
    waves: WAVE_CURVES[2],
    metaPerWave: 3,
    firstClearBonus: 40,
    seed: 333,
    introduces: ['splitter', 'stealth'],
  },
  {
    id: 'desert',
    name: 'Sidi Ridge',
    subtitle: 'Open ground, nowhere to hide',
    theme: 'desert',
    waypoints: [[-1, 2], [22, 2], [22, 5], [6, 5], [6, 8], [24, 8], [24, 11], [4, 11], [4, 13], [28, 13]],
    startingCash: 320,
    music: 'desert',
    waves: WAVE_CURVES[3],
    metaPerWave: 4,
    firstClearBonus: 50,
    seed: 444,
    introduces: ['healer'],
  },
  {
    id: 'rhine',
    name: 'Rhine Crossing',
    subtitle: 'The last bridge standing',
    theme: 'rhine',
    waypoints: [[-1, 2], [6, 2], [6, 12], [13, 12], [13, 3], [19, 3], [19, 10], [25, 10], [25, 2], [28, 2]],
    startingCash: 500,
    music: 'rhine',
    waves: WAVE_CURVES[4],
    metaPerWave: 4,
    firstClearBonus: 60,
    seed: 555,
    introduces: [],
  },
];
