import type { PixelArt } from '../../../assets/pixel';
import { WEST_ART_PALETTE as P } from './palette';

export const WEST_DECOR: Record<string, PixelArt> = {
  decor_barrel: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, R: '#7a5230', y: '#b89268' },
    frames: [['........', '........', '..oooooo', '..oRyRRR', '..oRRRRR', '..oRyRRR', '..oRRRRR', '..oRyRRR']],
  },
  decor_cactus: {
    mirrorX: true,
    palette: P,
    frames: [
      [
        '........',
        '........',
        '......oo',
        '.....oGG',
        '..o..oGG',
        '.oGo.oGG',
        '.oGooGGG',
        '.oGGGGGG',
        '.oGGGGGG',
        '..ooGGGG',
        '....oGGG',
        '....oGGG',
        '....oGGG',
        '....oooo',
        '........',
        '........',
      ],
    ],
  },
  decor_skull: {
    mirrorX: true,
    palette: P,
    frames: [
      [
        '........',
        '........',
        '........',
        '........',
        '.....ooo',
        '....owww',
        '...owoow',
        '...owooo',
        '...owwww',
        '....owww',
        '.....oww',
        '......oo',
        '........',
        '........',
        '........',
        '........',
      ],
    ],
  },
  decor_tumbleweed: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, m: '#7a6a3a', l: '#9c8a4a' },
    frames: [['........', '........', '.....oo.', '...omlmo', '..omlllm', '..olmlml', '..omllll', '..olmlmm']],
  },
  decor_rock_red: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, m: '#6e3224', l: '#a8523c', d: '#4a1f18' },
    frames: [['........', '........', '........', '.....ooo', '...oommm', '..ommlll', '..omlllm', '.omllmmm']],
  },
  decor_minecart: {
    palette: { ...P, m: '#4a5560', l: '#7d8f9c', d: '#2a3038', y: '#f0c040' },
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '...ooooooooo....',
        '...ollllllllo...',
        '...odyydyyddo...',
        '...oddddddddo...',
        '...ommmmmmmmo...',
        '....oooooooo....',
        '.....o......o...',
        '....ooo....ooo..',
        '....ooo....ooo..',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_crate_west: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, R: '#8a6a42', y: '#b89268' },
    frames: [['........', '........', '..oooooo', '..oRRRRR', '..oRyRRR', '..oRRyRR', '..oRRRyR', '..oRRRRy']],
  },
  decor_sleeper: {
    palette: { ...P, m: '#47301f', l: '#5c4326', B: '#7d8f9c' },
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        'oooooooooooooooo',
        'llllllllllllllll',
        'mmmmmmmmmmmmmmmm',
        'mmmmmmmmmmmmmmmm',
        'llllllllllllllll',
        'oooooooooooooooo',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
    ],
  },
};
