import type { PixelArt } from '../../../assets/pixel';
import { WW2_ART_PALETTE as P } from './palette';

export const WW2_DECOR: Record<string, PixelArt> = {
  decor_sandbags: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, R: '#8a7a56', y: '#a89868' },
    frames: [['........', '........', '..oooooo', '..oRRyRR', '..oyRRRy', '..oRRyRR', '..oyRRRy', '..oRRyRR']],
  },
  decor_barbedwire: {
    palette: { ...P, m: '#5f6647', l: '#8a9168' },
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '..o..........o..',
        '..m..........m..',
        '..m.l.l..l.l.m..',
        '..mlolollololmm.',
        '..m.l.l..l.l.m..',
        '..m..........m..',
        '..m..........m..',
        '..o..........o..',
        '................',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_ruin: {
    palette: { ...P, m: '#4a4a44', l: '#63635a', d: '#2b2820', r: '#6b2b1e' },
    frames: [
      [
        '................',
        '................',
        '...oo......oo...',
        '...omo....omo...',
        '...oldo...oldo..',
        '...oldo...oldo..',
        '..ooldooooldoo..',
        '..olddddddddlo..',
        '..oldrdddrdmlo..',
        '..olddddddddlo..',
        '..oldddddddmlo..',
        '..oooooooooooo..',
        '................',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_tree: {
    mirrorX: true,
    palette: { ...P, g: '#2f4429', G: '#3a5230', t: '#4a3b2a' },
    frames: [
      [
        '........',
        '.....ooo',
        '....ogGG',
        '...ogGGG',
        '..ogGGGG',
        '..ogGGGG',
        '...ogGGG',
        '....oggG',
        '.....ooo',
        '......ot',
        '......ot',
        '......ot',
        '.....oot',
        '........',
        '........',
        '........',
      ],
    ],
  },
  decor_crate_ammo: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, R: '#4a4f3a', y: '#6b8f3f' },
    frames: [['........', '........', '..oooooo', '..oRRRRR', '..oRyyRR', '..oRRRRR', '..oRyyRR', '..oRRRRR']],
  },
  decor_wreck: {
    palette: { ...P, d: '#2b2e22', m: '#4a4f3a', r: '#6b2b1e' },
    frames: [
      [
        '................',
        '................',
        '....oo..........',
        '...omdo.....o...',
        '...oddo....omo..',
        '....oo.....oddo.',
        '...........oo...',
        '......ooo.......',
        '.....ommmoo.....',
        '....omdddmmo....',
        '....odddrddo....',
        '.....oodddo.....',
        '.......ooo......',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_pontoon: {
    palette: { ...P, m: '#6e5a48', l: '#8a7156', d: '#4a3b2a' },
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        'oooooooooooooooo',
        'llllllllllllllll',
        'mmmmmmmmmmmmmmmm',
        'mmmmmmmmmmmmmmmm',
        'dddddddddddddddd',
        'oooooooooooooooo',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
    ],
  },
  decor_dune: {
    mirrorX: true,
    mirrorY: true,
    palette: { ...P, m: '#9c7f4e', l: '#c2a068', d: '#7a6338' },
    frames: [['........', '........', '........', '.....ooo', '...oommm', '..ommlll', '..omlllm', '.omllmmm']],
  },
};
